apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-repo-server-share
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/shares/repo"